# SPDX-FileCopyrightText: Copyright © 2025 Serban Giuroiu <giuroiu@gmail.com>
# SPDX-License-Identifier: MIT

[project]
name = "volant"
version = "0.0.2"
description = "Volant Script"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Serban Giuroiu", email = "giuroiu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.urls]
repository = "https://github.com/serban/volant"
changelog = "https://github.com/serban/volant/blob/master/CHANGELOG.md"

[dependency-groups]
dev = [
  "basedpyright>=1.39.9",
  "coverage>=7.15.2",
  "mypy>=2.3.0",
  "pdoc>=16.0.0",
  "pendulum>=3.2.0",
  "pyrefly>=1.1.1",
  "reuse>=6.2.0",
  "ruff>=0.16.0",
  "time-machine>=3.2.0",
  "ty>=0.0.65",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
