# SPDX-FileCopyrightText: Copyright © 2025 Serban Giuroiu <giuroiu@gmail.com>
# SPDX-License-Identifier: MIT

[project]
name = "volant"
version = "0.0.1"
description = "Volant Script"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Serban Giuroiu", email = "giuroiu@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.urls]
repository = "https://github.com/serban/volant"
changelog = "https://github.com/serban/volant/blob/master/CHANGELOG.md"

[dependency-groups]
dev = [
  "basedpyright>=1.36.1",
  "coverage>=7.13.0",
  "mypy>=1.19.1",
  "pdoc>=16.0.0",
  "pyrefly>=0.46.0",
  "reuse>=6.2.0",
  "ruff>=0.14.10",
  "time-machine>=3.2.0",
  "ty>=0.0.4",
]

[build-system]
requires = ["uv_build>=0.7.11,<0.8"]
build-backend = "uv_build"
