output-format = 'grouped'

indent-width = 2
line-length = 80

[format]
quote-style = 'single'

[lint]
extend-select = [
  'I',    # https://docs.astral.sh/ruff/rules/#isort-i
]
ignore = [
  'E741', # https://docs.astral.sh/ruff/rules/ambiguous-variable-name
]
